BEGIN;
-- Compatibility field remains only in markets.raw_payload; it is not canonical eligibility state.
ALTER TABLE markets DROP COLUMN fractional_trading_enabled;
CREATE TYPE realtime_health AS ENUM ('DISCONNECTED','CONNECTING','AUTHENTICATING','SUBSCRIBING','SNAPSHOTTING','HEALTHY','DEGRADED','GAP_DETECTED','STALE','BACKPRESSURED','RECONNECTING','FAILED');
CREATE TABLE realtime_connection_sessions (epoch uuid PRIMARY KEY, started_at timestamptz NOT NULL, ended_at timestamptz, endpoint text NOT NULL, state realtime_health NOT NULL, last_frame_at timestamptz, last_application_at timestamptz, reconnect_number integer NOT NULL, failure_code text);
CREATE TABLE realtime_subscriptions (epoch uuid REFERENCES realtime_connection_sessions(epoch), sid bigint NOT NULL, channel text NOT NULL, command_id bigint NOT NULL, market_tickers jsonb NOT NULL, use_yes_price boolean, state text NOT NULL, updated_at timestamptz NOT NULL, PRIMARY KEY(epoch,sid));
CREATE TABLE realtime_stream_health (epoch uuid REFERENCES realtime_connection_sessions(epoch), sid bigint, channel text NOT NULL, state realtime_health NOT NULL, last_seq bigint, queue_depth integer NOT NULL, processing_lag_ms numeric, unresolved_gaps integer NOT NULL, updated_at timestamptz NOT NULL, PRIMARY KEY(epoch,channel,sid));
CREATE TABLE market_ticker_latest (market_ticker text PRIMARY KEY REFERENCES markets(ticker), epoch uuid NOT NULL, sid bigint NOT NULL, seq bigint NOT NULL, price numeric, yes_bid numeric, yes_ask numeric, volume numeric NOT NULL, open_interest numeric NOT NULL, yes_bid_size numeric, yes_ask_size numeric, last_trade_size numeric, exchange_ts timestamptz NOT NULL, received_at timestamptz NOT NULL, ingest_latency_ms numeric NOT NULL, raw_payload jsonb NOT NULL);
CREATE TABLE public_trades (trade_id text PRIMARY KEY, market_ticker text NOT NULL REFERENCES markets(ticker), epoch uuid NOT NULL, sid bigint NOT NULL, seq bigint NOT NULL, yes_price numeric NOT NULL, no_price numeric NOT NULL, count numeric NOT NULL, taker_outcome_side text NOT NULL, taker_book_side text NOT NULL, exchange_ts timestamptz NOT NULL, received_at timestamptz NOT NULL, raw_payload jsonb NOT NULL);
CREATE TABLE realtime_book_latest (market_ticker text PRIMARY KEY REFERENCES markets(ticker), epoch uuid NOT NULL, sid bigint NOT NULL, seq bigint NOT NULL, state realtime_health NOT NULL, yes_levels jsonb NOT NULL, no_levels_unified_yes_scale jsonb NOT NULL, best_yes_bid numeric, best_yes_ask numeric, best_bid_size numeric, best_ask_size numeric, exchange_ts timestamptz, received_at timestamptz NOT NULL, price_structure_hash text NOT NULL);
CREATE TABLE realtime_data_gaps (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, epoch uuid NOT NULL, sid bigint, channel text NOT NULL, expected_seq bigint, actual_seq bigint, affected_markets jsonb NOT NULL, started_at timestamptz NOT NULL, resolved_at timestamptz, recovery_method text, detail text NOT NULL);
CREATE TABLE realtime_recovery_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, gap_id bigint REFERENCES realtime_data_gaps(id), epoch uuid NOT NULL, sid bigint, method text NOT NULL, attempted_at timestamptz NOT NULL, succeeded boolean NOT NULL, detail text NOT NULL);
CREATE TABLE market_lifecycle_events (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, market_ticker text NOT NULL, epoch uuid NOT NULL, sid bigint NOT NULL, seq bigint NOT NULL, channel text NOT NULL, event_type text NOT NULL, result text, settlement_value numeric, exchange_ts timestamptz NOT NULL, received_at timestamptz NOT NULL, metadata_refresh_required boolean NOT NULL, raw_payload jsonb NOT NULL, UNIQUE(epoch,sid,seq));
CREATE TABLE raw_realtime_archive_manifests (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, epoch uuid NOT NULL, channel text NOT NULL, object_key text NOT NULL UNIQUE, first_received_at timestamptz NOT NULL, last_received_at timestamptz NOT NULL, event_count integer NOT NULL, compressed_bytes bigint NOT NULL, sha256 text NOT NULL, gap_markers integer NOT NULL, retention_until timestamptz NOT NULL);
CREATE INDEX public_trades_market_time_idx ON public_trades(market_ticker,exchange_ts DESC);
CREATE INDEX lifecycle_market_time_idx ON market_lifecycle_events(market_ticker,exchange_ts DESC);
COMMIT;
