-- M6 immutable historical acquisition and point-in-time replay lineage.
CREATE TABLE historical_cutoff_observations (id text PRIMARY KEY, observed_at timestamptz NOT NULL, market_settled_ts timestamptz NOT NULL, trades_created_ts timestamptz NOT NULL, orders_updated_ts timestamptz NOT NULL, spec_version text NOT NULL, backward_warning boolean NOT NULL);
CREATE TABLE historical_archive_manifests (manifest_id text PRIMARY KEY, provider text NOT NULL, endpoint text NOT NULL, request_parameters jsonb NOT NULL, retrieved_at timestamptz NOT NULL, page_number integer NOT NULL, cursor_in text, cursor_out text, record_count integer NOT NULL, raw_hash text NOT NULL, normalized_hash text NOT NULL, parser_version text NOT NULL, spec_version text NOT NULL, succeeded boolean NOT NULL, failure text, archive_location text);
CREATE TABLE replay_events (event_id text PRIMARY KEY, event_type text NOT NULL, provider text NOT NULL, source_event_at timestamptz, source_publish_at timestamptz, provider_receive_at timestamptz, actual_bot_ingest_at timestamptz NOT NULL, replay_available_at timestamptz, availability_basis text NOT NULL, availability_quality text NOT NULL, assumed_latency interval, provider_sequence bigint, receive_monotonic_sequence bigint, ingest_sequence bigint, entity_ids jsonb NOT NULL, raw_hash text NOT NULL, normalized_hash text NOT NULL, parser_version text NOT NULL, schema_version text NOT NULL, archive_manifest_id text REFERENCES historical_archive_manifests(manifest_id), gap_marker boolean NOT NULL DEFAULT false, correction_of_event_id text REFERENCES replay_events(event_id));
CREATE INDEX replay_events_available_idx ON replay_events (replay_available_at, provider_sequence, ingest_sequence, event_id);
CREATE TABLE replay_datasets (dataset_id text PRIMARY KEY, created_at timestamptz NOT NULL, start_at timestamptz NOT NULL, end_at timestamptz NOT NULL, manifest jsonb NOT NULL, content_hash text NOT NULL, code_git_sha text NOT NULL);
CREATE TABLE replay_dataset_sources (dataset_id text REFERENCES replay_datasets(dataset_id), manifest_id text REFERENCES historical_archive_manifests(manifest_id), PRIMARY KEY(dataset_id, manifest_id));
CREATE TABLE replay_gaps (gap_id text PRIMARY KEY, dataset_id text REFERENCES replay_datasets(dataset_id), gap_type text NOT NULL, severity text NOT NULL, start_at timestamptz NOT NULL, end_at timestamptz, detail text NOT NULL);
CREATE TABLE replay_checkpoints (checkpoint_id text PRIMARY KEY, dataset_id text REFERENCES replay_datasets(dataset_id), replay_at timestamptz NOT NULL, last_event_id text, state_hash text NOT NULL, state_location text NOT NULL);
CREATE TABLE settlement_labels (label_id text PRIMARY KEY, market_ticker text NOT NULL, rules_version text NOT NULL, result text NOT NULL, settlement_value numeric NOT NULL, settlement_at timestamptz NOT NULL, finalized_at timestamptz, state text NOT NULL, raw_manifest_id text REFERENCES historical_archive_manifests(manifest_id), retrieved_at timestamptz NOT NULL, supersedes_label_id text REFERENCES settlement_labels(label_id));
CREATE TABLE rules_reconstruction_versions (id text PRIMARY KEY, market_ticker text NOT NULL, quality text NOT NULL, effective_at timestamptz, observed_at timestamptz NOT NULL, source_hash text NOT NULL);
CREATE TABLE fee_reconstruction_versions (id text PRIMARY KEY, quality text NOT NULL, effective_at timestamptz, observed_at timestamptz NOT NULL, rule_hash text NOT NULL);
