-- M7 immutable public-evidence and provider-run lineage. LLM output has no production influence.
CREATE TABLE prompt_versions (prompt_version text PRIMARY KEY, prompt_hash text NOT NULL, template text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE schema_versions (schema_version text PRIMARY KEY, schema_hash text NOT NULL, schema jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE evidence_bundles (bundle_id text PRIMARY KEY, created_at timestamptz NOT NULL, replay_at timestamptz NOT NULL, market_ticker text NOT NULL, rules_version text NOT NULL, rules_hash text NOT NULL, source_manifest jsonb NOT NULL, content_hash text NOT NULL, builder_version text NOT NULL);
CREATE TABLE llm_inference_runs (run_id text PRIMARY KEY, bundle_id text REFERENCES evidence_bundles(bundle_id), provider text NOT NULL, requested_model text NOT NULL, returned_model text NOT NULL, prompt_version text REFERENCES prompt_versions(prompt_version), schema_version text REFERENCES schema_versions(schema_version), started_at timestamptz NOT NULL, completed_at timestamptz NOT NULL, source_available_at timestamptz NOT NULL, mode text NOT NULL, status text NOT NULL, refusal text, incomplete boolean NOT NULL, provider_error text, usage jsonb NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0));
CREATE TABLE llm_inference_attempts (attempt_id text PRIMARY KEY, run_id text REFERENCES llm_inference_runs(run_id), attempt_number integer NOT NULL, status text NOT NULL, raw_response_hash text, error text, created_at timestamptz NOT NULL);
CREATE TABLE atomic_claims (claim_id text PRIMARY KEY, bundle_id text REFERENCES evidence_bundles(bundle_id), run_id text REFERENCES llm_inference_runs(run_id), claim_type text NOT NULL, epistemic_status text NOT NULL, claim jsonb NOT NULL, status text NOT NULL, supersedes_claim_id text REFERENCES atomic_claims(claim_id));
CREATE TABLE claim_citations (citation_id text PRIMARY KEY, claim_id text REFERENCES atomic_claims(claim_id), source_id text NOT NULL, document_hash text NOT NULL, locator_type text NOT NULL, start_offset integer NOT NULL, end_offset integer NOT NULL, exact_text text NOT NULL);
CREATE TABLE citation_validations (validation_id text PRIMARY KEY, citation_id text REFERENCES claim_citations(citation_id), validator_version text NOT NULL, span_exists boolean NOT NULL, numeric_consistent boolean NOT NULL, attribution_consistent boolean NOT NULL, entailment text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE contract_interpretations (interpretation_id text PRIMARY KEY, market_ticker text NOT NULL, rules_version text NOT NULL, interpretation jsonb NOT NULL, status text NOT NULL, created_at timestamptz NOT NULL, supersedes_id text REFERENCES contract_interpretations(interpretation_id));
CREATE TABLE claim_contract_relations (claim_id text REFERENCES atomic_claims(claim_id), interpretation_id text REFERENCES contract_interpretations(interpretation_id), relation text NOT NULL, validator_version text NOT NULL, PRIMARY KEY(claim_id, interpretation_id));
CREATE TABLE evidence_contradictions (contradiction_id text PRIMARY KEY, claim_a text REFERENCES atomic_claims(claim_id), claim_b text REFERENCES atomic_claims(claim_id), contradiction_type text NOT NULL, detail jsonb NOT NULL);
CREATE TABLE evidence_abstentions (abstention_id text PRIMARY KEY, run_id text REFERENCES llm_inference_runs(run_id), reason text NOT NULL, detail text NOT NULL);
CREATE TABLE provider_usage (usage_id text PRIMARY KEY, run_id text REFERENCES llm_inference_runs(run_id), provider text NOT NULL, model text NOT NULL, input_tokens bigint, output_tokens bigint, cached_tokens bigint, estimated_cost numeric, actual_cost numeric, pricing_version text);
CREATE TABLE inference_cache (cache_key text PRIMARY KEY, run_id text REFERENCES llm_inference_runs(run_id), created_at timestamptz NOT NULL);
CREATE TABLE evidence_validation_events (event_id text PRIMARY KEY, claim_id text REFERENCES atomic_claims(claim_id), previous_status text, new_status text NOT NULL, validator_version text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE llm_eval_runs (eval_id text PRIMARY KEY, split text NOT NULL, model text NOT NULL, prompt_version text NOT NULL, schema_version text NOT NULL, metrics jsonb NOT NULL, artifact_count integer NOT NULL, created_at timestamptz NOT NULL);
