-- M8 immutable research forecasts. No production approval, sizing, risk, or execution fields.
CREATE TABLE model_registry (model_id text, version text, family text NOT NULL, target text NOT NULL, model_type text NOT NULL, forecast_kind text NOT NULL, feature_schema text NOT NULL, training_window tstzrange NOT NULL, training_dataset_manifest text NOT NULL, calibration_relationship text NOT NULL, code_version text NOT NULL, parameters jsonb NOT NULL, artifact_hash text NOT NULL, status text NOT NULL CHECK(status IN ('DEVELOPMENT','RESEARCH','SHADOW','CHALLENGER','RETIRED','QUARANTINED')), created_at timestamptz NOT NULL, PRIMARY KEY(model_id,version));
CREATE TABLE model_cards (model_id text, version text, card jsonb NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0), PRIMARY KEY(model_id,version));
CREATE TABLE feature_schemas (schema_id text PRIMARY KEY, version text NOT NULL, schema jsonb NOT NULL, content_hash text NOT NULL);
CREATE TABLE feature_snapshots (snapshot_id text PRIMARY KEY, forecast_at timestamptz NOT NULL, schema_version text NOT NULL, features jsonb NOT NULL, content_hash text NOT NULL);
CREATE TABLE forecast_runs (run_id text PRIMARY KEY, model_id text NOT NULL, model_version text NOT NULL, checkpoint_at timestamptz NOT NULL, status text NOT NULL, failure text, created_at timestamptz NOT NULL);
CREATE TABLE frozen_forecasts (forecast_id text PRIMARY KEY, market_ticker text NOT NULL, event_id text NOT NULL, series_id text NOT NULL, family text NOT NULL, forecast_kind text NOT NULL, issued_at timestamptz NOT NULL, target_at timestamptz NOT NULL, model_id text NOT NULL, model_version text NOT NULL, feature_snapshot_id text REFERENCES feature_snapshots(snapshot_id), raw_probability numeric, calibrated_probability numeric, lower_probability numeric, upper_probability numeric, market_reference_id text, abstention_reason text, research_status text NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0), content_hash text NOT NULL);
CREATE INDEX frozen_forecasts_checkpoint_idx ON frozen_forecasts(event_id,issued_at,forecast_kind);
CREATE TABLE forecast_distributions (forecast_id text PRIMARY KEY REFERENCES frozen_forecasts(forecast_id), distribution_type text NOT NULL, parameters jsonb NOT NULL, artifact_hash text NOT NULL);
CREATE TABLE forecast_abstentions (forecast_id text PRIMARY KEY REFERENCES frozen_forecasts(forecast_id), reason text NOT NULL, detail text NOT NULL);
CREATE TABLE calibrator_versions (calibrator_id text PRIMARY KEY, version text NOT NULL, training_cutoff timestamptz NOT NULL, training_event_count integer NOT NULL, effective_sample_size numeric NOT NULL, family text NOT NULL, horizon_bucket text NOT NULL, method text NOT NULL, parameters jsonb NOT NULL, artifact_hash text NOT NULL);
CREATE TABLE calibration_training_sets (calibrator_id text REFERENCES calibrator_versions(calibrator_id), dataset_manifest text NOT NULL, event_ids_hash text NOT NULL, PRIMARY KEY(calibrator_id,dataset_manifest));
CREATE TABLE market_reference_forecasts (reference_id text PRIMARY KEY, snapshot_at timestamptz NOT NULL, yes_bid numeric NOT NULL, yes_ask numeric NOT NULL, no_bid numeric NOT NULL, no_ask numeric NOT NULL, spread numeric NOT NULL, reference_probability numeric NOT NULL, construction_method text NOT NULL, age_ms integer NOT NULL);
CREATE TABLE forecast_scores (forecast_id text REFERENCES frozen_forecasts(forecast_id), label_version text NOT NULL, brier numeric NOT NULL, log_loss numeric NOT NULL, clipping_used boolean NOT NULL, market_brier numeric, market_log_loss numeric, PRIMARY KEY(forecast_id,label_version));
CREATE TABLE model_evaluation_runs (evaluation_id text PRIMARY KEY, dataset_manifest text NOT NULL, development_period tstzrange NOT NULL, validation_period tstzrange NOT NULL, untouched_period tstzrange, synthetic boolean NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE model_evaluation_metrics (evaluation_id text REFERENCES model_evaluation_runs(evaluation_id), family text NOT NULL, model_id text NOT NULL, horizon text NOT NULL, probability_bucket text NOT NULL, liquidity_regime text NOT NULL, metrics jsonb NOT NULL, PRIMARY KEY(evaluation_id,family,model_id,horizon,probability_bucket,liquidity_regime));
CREATE TABLE forecast_checkpoint_policies (policy_id text PRIMARY KEY, family text NOT NULL, version text NOT NULL, horizons jsonb NOT NULL, requirements jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE weather_source_records (record_id text PRIMARY KEY, station_id text NOT NULL, source_role text NOT NULL, issued_at timestamptz NOT NULL, valid_at timestamptz NOT NULL, replay_available_at timestamptz NOT NULL, payload_hash text NOT NULL, correction_of text REFERENCES weather_source_records(record_id));
CREATE TABLE economic_release_vintages (vintage_id text PRIMARY KEY, target text NOT NULL, series_id text NOT NULL, reference_period text NOT NULL, scheduled_at timestamptz NOT NULL, published_at timestamptz NOT NULL, replay_available_at timestamptz NOT NULL, value numeric NOT NULL, unit text NOT NULL, revision_number integer NOT NULL, revises_vintage_id text REFERENCES economic_release_vintages(vintage_id));
