-- M9 immutable research governance; no production influence or financial-risk fields.
CREATE TABLE ablation_runs (run_id text PRIMARY KEY, dataset_manifest text NOT NULL, target_type text NOT NULL, configuration_id text NOT NULL, synthetic boolean NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE ablation_results (result_id text PRIMARY KEY, run_id text REFERENCES ablation_runs(run_id), component_type text NOT NULL, component_id text NOT NULL, segment jsonb NOT NULL, full_score jsonb NOT NULL, ablated_score jsonb NOT NULL, counts jsonb NOT NULL, observed_contribution numeric NOT NULL);
CREATE TABLE source_evaluations (evaluation_id text PRIMARY KEY, stable_source_id text NOT NULL, target_type text NOT NULL, segment jsonb NOT NULL, quality jsonb NOT NULL, dataset_manifest text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE model_evaluations (evaluation_id text PRIMARY KEY, model_id text NOT NULL, champion_id text, windows jsonb NOT NULL, same_event_manifest text NOT NULL, metrics jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE performance_intervals (interval_id text PRIMARY KEY, evaluation_id text NOT NULL, method text NOT NULL, point numeric NOT NULL, lower numeric NOT NULL, upper numeric NOT NULL, event_count integer NOT NULL, evidence_state text NOT NULL);
CREATE TABLE redundancy_metrics (metric_id text PRIMARY KEY, source_a text NOT NULL, source_b text NOT NULL, claim_overlap numeric NOT NULL, common_root_fraction numeric NOT NULL, timing_correlation numeric NOT NULL, residual_correlation numeric NOT NULL, same_primary_dependence numeric NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE drift_metrics (metric_id text PRIMARY KEY, component_id text NOT NULL, dimension text NOT NULL, baseline numeric NOT NULL, current_value numeric NOT NULL, warning_threshold numeric NOT NULL, quarantine_threshold numeric NOT NULL, action text NOT NULL, observed_at timestamptz NOT NULL);
CREATE TABLE learning_proposals (proposal_id text PRIMARY KEY, proposal_type text NOT NULL, component_id text NOT NULL, previous_state jsonb NOT NULL, proposed_state jsonb NOT NULL, evidence_window tstzrange, effective_sample_size numeric NOT NULL, uncertainty jsonb, rationale text NOT NULL, rollback_target text NOT NULL, status text NOT NULL, human_approval_required boolean NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0), created_at timestamptz NOT NULL);
CREATE TABLE learning_proposal_evidence (proposal_id text REFERENCES learning_proposals(proposal_id), evidence_id text NOT NULL, PRIMARY KEY(proposal_id,evidence_id));
CREATE TABLE learning_configurations (configuration_id text PRIMARY KEY, version text NOT NULL, effective_at timestamptz NOT NULL, predecessor_id text REFERENCES learning_configurations(configuration_id), mode text NOT NULL, configuration jsonb NOT NULL, content_hash text NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0));
CREATE TABLE research_budgets (budget_id text PRIMARY KEY, configuration_id text REFERENCES learning_configurations(configuration_id), exploration_floor numeric NOT NULL, allocations jsonb NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE family_tournament_runs (run_id text PRIMARY KEY, dataset_manifest text NOT NULL, synthetic boolean NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE family_scores (run_id text REFERENCES family_tournament_runs(run_id), family text NOT NULL, metrics jsonb NOT NULL, research_score numeric NOT NULL, capital_allocation text NOT NULL DEFAULT 'NOT DETERMINED', PRIMARY KEY(run_id,family));
CREATE TABLE quarantine_events (event_id text PRIMARY KEY, component_id text NOT NULL, component_type text NOT NULL, reason text NOT NULL, evidence jsonb NOT NULL, proposed_at timestamptz NOT NULL, approved_at timestamptz);
CREATE TABLE rollback_events (event_id text PRIMARY KEY, from_configuration text REFERENCES learning_configurations(configuration_id), to_configuration text REFERENCES learning_configurations(configuration_id), reason text NOT NULL, happened_at timestamptz NOT NULL);
CREATE TABLE learning_events (event_id text PRIMARY KEY, happened_at timestamptz NOT NULL, actor text NOT NULL, event_type text NOT NULL, previous_configuration text, new_configuration text, evidence jsonb NOT NULL, reason text NOT NULL, status text NOT NULL);
