-- M10 immutable research economics; no execution, sizing, risk authorization, or writes.
CREATE TABLE fee_policies (policy_id text PRIMARY KEY, fee_type text NOT NULL, multiplier numeric NOT NULL, effective_at timestamptz NOT NULL, retired_at timestamptz, formula_version text NOT NULL, source_reference text NOT NULL, verified boolean NOT NULL, policy jsonb NOT NULL);
CREATE TABLE fee_calculations (calculation_id text PRIMARY KEY, policy_id text REFERENCES fee_policies(policy_id), theoretical_fee numeric NOT NULL, rounding_component numeric NOT NULL, expected_rebate numeric NOT NULL, total_fee numeric NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE depth_curves (curve_id text PRIMARY KEY, market_ticker text NOT NULL, outcome_side text NOT NULL, snapshot_at timestamptz NOT NULL, raw_levels jsonb NOT NULL, normalized_levels jsonb NOT NULL, content_hash text NOT NULL);
CREATE TABLE slippage_estimates (estimate_id text PRIMARY KEY, curve_id text REFERENCES depth_curves(curve_id), method text NOT NULL, requested_quantity numeric NOT NULL, filled_quantity numeric NOT NULL, average_price numeric, worst_price numeric, unfilled numeric NOT NULL);
CREATE TABLE fill_probability_estimates (estimate_id text PRIMARY KEY, method text NOT NULL, probability numeric, quality text NOT NULL, model_version text NOT NULL, created_at timestamptz NOT NULL);
CREATE TABLE liquidity_diagnostics (diagnostic_id text PRIMARY KEY, market_ticker text NOT NULL, snapshot_at timestamptz NOT NULL, components jsonb NOT NULL);
CREATE TABLE information_decay_estimates (estimate_id text PRIMARY KEY, candidate_time timestamptz NOT NULL, classification text NOT NULL, factor numeric NOT NULL, inputs jsonb NOT NULL);
CREATE TABLE correlation_clusters (cluster_id text PRIMARY KEY, underlying_event_id text NOT NULL, markets jsonb NOT NULL, mutually_exclusive boolean NOT NULL, exhaustive boolean NOT NULL, duplicate_thesis boolean NOT NULL);
CREATE TABLE trade_candidates (candidate_id text PRIMARY KEY, created_at timestamptz NOT NULL, market_ticker text NOT NULL, event_id text NOT NULL, forecast_id text NOT NULL, forecast_kind text NOT NULL, outcome_side text NOT NULL, analysis_type text NOT NULL, decision_state text NOT NULL CHECK(decision_state IN ('REJECTED','INCOMPLETE','WATCH','RESEARCH_CANDIDATE','HIGH_PRIORITY_RESEARCH_CANDIDATE')), candidate jsonb NOT NULL, research_only boolean NOT NULL CHECK(research_only), production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0), content_hash text NOT NULL);
CREATE TABLE candidate_economic_components (candidate_id text REFERENCES trade_candidates(candidate_id), component_name text NOT NULL, component_value numeric, quality text, PRIMARY KEY(candidate_id,component_name));
CREATE TABLE candidate_rejections (candidate_id text REFERENCES trade_candidates(candidate_id), reason text NOT NULL, PRIMARY KEY(candidate_id,reason));
CREATE TABLE opportunity_rankings (ranking_id text PRIMARY KEY, generated_at timestamptz NOT NULL, policy_version text NOT NULL, candidate_ids jsonb NOT NULL, component_manifest jsonb NOT NULL);
CREATE TABLE opportunity_datasets (dataset_id text PRIMARY KEY, start_at timestamptz NOT NULL, end_at timestamptz NOT NULL, manifest jsonb NOT NULL, content_hash text NOT NULL);
CREATE TABLE cross_venue_opportunities (observation_id text PRIMARY KEY, semantic_match text NOT NULL, observation jsonb NOT NULL, research_state text NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0));
CREATE TABLE hypothetical_execution_scenarios (scenario_id text PRIMARY KEY, candidate_id text REFERENCES trade_candidates(candidate_id), analysis_type text NOT NULL, assumptions jsonb NOT NULL, conditional_ev numeric, attempt_ev numeric, research_only boolean NOT NULL CHECK(research_only));
