-- M11 historical/synthetic execution research only; never exchange orders.
CREATE TABLE execution_assumption_policies (policy_id text NOT NULL, version text NOT NULL, scenario text NOT NULL CHECK(scenario IN ('OPTIMISTIC','BASE','ADVERSE')), effective_at timestamptz NOT NULL, assumptions jsonb NOT NULL, content_hash text NOT NULL, PRIMARY KEY(policy_id,version));
CREATE TABLE latency_models (latency_model_id text PRIMARY KEY, version text NOT NULL, provenance text NOT NULL CHECK(provenance IN ('MEASURED','SIMULATION_ASSUMPTION')), quantiles jsonb NOT NULL, content_hash text NOT NULL);
CREATE TABLE queue_models (queue_model_id text PRIMARY KEY, version text NOT NULL, quality text NOT NULL, cancellation_credit numeric NOT NULL, limitations jsonb NOT NULL, content_hash text NOT NULL);
CREATE TABLE backtest_runs (run_id text PRIMARY KEY, opportunity_dataset_id text NOT NULL REFERENCES opportunity_datasets(dataset_id), replay_dataset_id text NOT NULL, execution_policy_versions jsonb NOT NULL, manifest jsonb NOT NULL, started_at timestamptz NOT NULL, completed_at timestamptz NOT NULL, content_hash text NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0));
CREATE TABLE simulated_orders (simulated_order_id text PRIMARY KEY CHECK(simulated_order_id LIKE 'sim-%'), run_id text NOT NULL REFERENCES backtest_runs(run_id), candidate_id text NOT NULL REFERENCES trade_candidates(candidate_id), scenario text NOT NULL, strategy text NOT NULL, candidate_time timestamptz NOT NULL, decision_time timestamptz NOT NULL, submit_time timestamptz NOT NULL, arrival_time timestamptz NOT NULL, state text NOT NULL, initial_quantity numeric NOT NULL, remaining_quantity numeric NOT NULL, queue_quality text NOT NULL, queue_assumption jsonb NOT NULL, production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0));
CREATE TABLE simulated_order_events (simulated_event_id text PRIMARY KEY, simulated_order_id text NOT NULL REFERENCES simulated_orders(simulated_order_id), event_time timestamptz NOT NULL, replay_sequence bigint, event_type text NOT NULL, state_before text NOT NULL, state_after text NOT NULL, lineage jsonb NOT NULL);
CREATE TABLE simulated_fills (simulated_fill_id text PRIMARY KEY CHECK(simulated_fill_id LIKE 'sim-fill-%'), simulated_order_id text NOT NULL REFERENCES simulated_orders(simulated_order_id), fill_time timestamptz NOT NULL, outcome_side text NOT NULL, book_side text NOT NULL, price numeric NOT NULL, quantity numeric NOT NULL, maker boolean NOT NULL, fee numeric NOT NULL, cumulative_fill numeric NOT NULL, remaining_quantity numeric NOT NULL, replay_sequence bigint NOT NULL, lineage jsonb NOT NULL);
CREATE TABLE simulated_cancellations (simulated_cancellation_id text PRIMARY KEY, simulated_order_id text NOT NULL REFERENCES simulated_orders(simulated_order_id), requested_at timestamptz NOT NULL, effective_at timestamptz, trigger text NOT NULL, fills_during_latency jsonb NOT NULL);
CREATE TABLE markout_observations (markout_id text PRIMARY KEY, simulated_fill_id text NOT NULL REFERENCES simulated_fills(simulated_fill_id), horizon_ms bigint NOT NULL, reference_time timestamptz NOT NULL, market_reference numeric NOT NULL, executable_unwind numeric, normalized_markout numeric NOT NULL);
CREATE TABLE execution_outcome_unknowns (unknown_id text PRIMARY KEY, simulated_order_id text NOT NULL REFERENCES simulated_orders(simulated_order_id), occurred_at timestamptz NOT NULL, reason text NOT NULL, gap_lineage jsonb NOT NULL);
CREATE TABLE execution_metrics (metric_id text PRIMARY KEY, run_id text NOT NULL REFERENCES backtest_runs(run_id), scenario text NOT NULL, strategy text NOT NULL, family text NOT NULL, horizon text NOT NULL, event_counts jsonb NOT NULL, metrics jsonb NOT NULL);
CREATE TABLE drawdown_series (run_id text NOT NULL REFERENCES backtest_runs(run_id), point_time timestamptz NOT NULL, cumulative_pnl numeric NOT NULL, peak numeric NOT NULL, drawdown numeric NOT NULL, PRIMARY KEY(run_id,point_time));
CREATE TABLE capacity_curves (capacity_id text PRIMARY KEY, run_id text NOT NULL REFERENCES backtest_runs(run_id), strategy text NOT NULL, hypothetical_quantity numeric NOT NULL, fill_rate numeric NOT NULL, average_slippage numeric, average_attempt_value numeric, label text NOT NULL CHECK(label='RESEARCH CAPACITY, NOT POSITION SIZING'));
CREATE TABLE advancement_evaluations (evaluation_id text PRIMARY KEY, run_id text NOT NULL REFERENCES backtest_runs(run_id), base_result jsonb NOT NULL, adverse_result jsonb NOT NULL, sample_evidence jsonb NOT NULL, advancement_state text NOT NULL CHECK(advancement_state IN ('FAIL','INCONCLUSIVE','PASSES_EXECUTION_RESEARCH_GATE')), production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0));
CREATE TABLE cross_venue_leg_simulations (simulation_id text PRIMARY KEY, run_id text NOT NULL REFERENCES backtest_runs(run_id), kalshi_arrival timestamptz NOT NULL, polymarket_arrival timestamptz NOT NULL, state text NOT NULL, assumptions jsonb NOT NULL, label text NOT NULL CHECK(label='HYPOTHETICAL CROSS-VENUE SIMULATION'), production_influence numeric NOT NULL DEFAULT 0 CHECK(production_influence=0));
CREATE TABLE execution_model_calibration (calibration_id text PRIMARY KEY, model_type text NOT NULL, model_version text NOT NULL, status text NOT NULL CHECK(status IN ('UNVALIDATED','SYNTHETIC_VALIDATED','HISTORICAL_RESEARCH_VALIDATED','REAL_ORDER_VALIDATED')), targets jsonb NOT NULL, real_observation_count integer NOT NULL DEFAULT 0, content_hash text NOT NULL);
CREATE TABLE real_queue_observation_research (observation_id text PRIMARY KEY, observed_order_reference text NOT NULL, observation_time timestamptz NOT NULL, queue_position_fp numeric NOT NULL, remaining_quantity_fp numeric NOT NULL, price numeric NOT NULL, subsequent_fills jsonb NOT NULL, cancellation jsonb NOT NULL, market_state jsonb NOT NULL, validation_status text NOT NULL DEFAULT 'NOT_VERIFIED');
