"""M26A owner-facing research-agent domain contracts."""

from .attribution import OpportunityAttribution, receipt_identity
from .beliefs import CurrentAgentBelief, FreshnessPolicy, current_belief
from .domain import (
    AGENT_REGISTRY,
    AgentDefinition,
    AutonomyMode,
    DecisionReceipt,
    ImplementationAvailability,
    ResearchDecision,
    agent_by_id,
    explain_decision,
)
from .evaluation import (
    AgentPerformance,
    EvaluationDatasetManifest,
    EvaluationEligibility,
    EvaluationTarget,
    ReceiptEvaluation,
    calibration,
    effective_evaluations,
    evaluate_receipt,
    performance,
)
from .evaluation_store import EvaluationStore, EvaluationStoreError
from .event_evidence import (
    EvaluatedMarketEventBinding,
    EventEvidenceAssessment,
    EventEvidenceManifest,
    EvidenceSufficiencyPolicy,
    ObservationAuthorityState,
    UniverseEventObservation,
    aggregate_market_differences_by_exchange_event,
    assess_manifest,
    bind_market_event,
    manifest_from_evaluation_store,
    manifest_from_pairwise_comparison,
)
from .store import DecisionReceiptStore, DecisionReceiptStoreError

__all__ = [
    "AGENT_REGISTRY",
    "AgentDefinition",
    "AgentPerformance",
    "AutonomyMode",
    "CurrentAgentBelief",
    "DecisionReceipt",
    "DecisionReceiptStore",
    "DecisionReceiptStoreError",
    "EvaluatedMarketEventBinding",
    "EvaluationDatasetManifest",
    "EvaluationEligibility",
    "EvaluationStore",
    "EvaluationStoreError",
    "EvaluationTarget",
    "EventEvidenceAssessment",
    "EventEvidenceManifest",
    "EvidenceSufficiencyPolicy",
    "FreshnessPolicy",
    "ImplementationAvailability",
    "ObservationAuthorityState",
    "OpportunityAttribution",
    "ReceiptEvaluation",
    "ResearchDecision",
    "UniverseEventObservation",
    "agent_by_id",
    "aggregate_market_differences_by_exchange_event",
    "assess_manifest",
    "bind_market_event",
    "calibration",
    "current_belief",
    "effective_evaluations",
    "evaluate_receipt",
    "explain_decision",
    "manifest_from_evaluation_store",
    "manifest_from_pairwise_comparison",
    "performance",
    "receipt_identity",
]
